### ISSUE TITLE
Возможность задать категорию содержащую подкатегории в бюджете

### ISSUE THREAD

**Issue by Abyss777** [ivang7/fingen#8]
Добрый день
Я смотрю вы разбирались в приложении и немного пилите его
Нет желания его еще немного доработать?
На текущий момент в бюджете можно задать сумму у категории только нижнего уровня, зачастую неудобно так детализировать бюджет.
Было бы круто иметь возможность задать сумму для категорий боле высоких уровней.
Спасибо

**Comment by ivang7** [comment]
Здраствуйте.
Сам бюджетом с целью соблюдению лимита расходов не пользовался.
Подобное предложение кажется не логичным, т.к. в иерархичной структуре родительские узлы являются суммой дочерних.

В вашем случае, решением будет установка необходимого лимита на один любой дочерний (я так понимаю, что по ним соблюдение будет не важно) - тогда на необходимом уровне будет нужная сумма.

Именно задание бюджета на родительском, с технической реализации вижу только распределением введенной суммы на дочернии: в равной степени на всех, либо пропорционально фактическим тратам в прошлом / текущем периоде.

**Comment by Abyss777** [comment]
Если задавать на каком-то более низком уровне, то бюджет превращается в красно-зелёную портянку. Это не позволяет бегло оценить превышения, нужно вникать в каждую цифру.
Если бы была возможность сворачивать и раскрывать категории в отображении бюджета, было бы нагляднее и вариант с заданием сумм на более низком уровне был бы подходящим.

**Comment by unwo** [comment]
Я использую бюджет по категориям и вносил в код небольшие изменения. Вот diff относительно master ветки:
`app/src/main/java/com/yoshione/fingen/FragmentBudget.java           | 3 +--
 app/src/main/java/com/yoshione/fingen/adapter/AdapterBudget.java    | 2 +-
 app/src/main/java/com/yoshione/fingen/dao/CategoriesDAO.java        | 1 -
 app/src/main/java/com/yoshione/fingen/managers/CategoryManager.java | 1 -
 4 files changed, 2 insertions(+), 5 deletions(-)

diff --git a/app/src/main/java/com/yoshione/fingen/FragmentBudget.java b/app/src/main/java/com/yoshione/fingen/FragmentBudget.java
index b2fcd75..8f7a24d 100644
--- a/app/src/main/java/com/yoshione/fingen/FragmentBudget.java
+++ b/app/src/main/java/com/yoshione/fingen/FragmentBudget.java
@@ -429,7 +429,6 @@ public class FragmentBudget extends Fragment implements AdapterBudget.IOnItemCli
                 CategoryManager.convertListToTree(CategoriesDAO.getInstance(getActivity())
                         .getAllCategoriesWithPlanFact(mYear, mMonth))
                         .addDebtsCategories(getActivity(), mYear, mMonth)
-                        .removeEmptySums()
         );
         Log.d(TAG, "Load plan and fact for categories " + String.valueOf(System.currentTimeMillis() - time));
 
@@ -814,7 +813,7 @@ public class FragmentBudget extends Fragment implements AdapterBudget.IOnItemCli
             CNode node = adapter.getmTree().getChildrenAtFlatPos(position);
             if (node != null) {
                 SumsByCabbage sumsByCabbage = node.getmCategory().getBudget().getmSums().getSumsByCabbageId(cabbageId);
-                boolean fullUpdt = false;
+                boolean fullUpdt = true;
                 if (sumsByCabbage == null) {
                     sumsByCabbage = new SumsByCabbage(cabbageId, BigDecimal.ZERO, BigDecimal.ZERO);
                     fullUpdt = true;
diff --git a/app/src/main/java/com/yoshione/fingen/adapter/AdapterBudget.java b/app/src/main/java/com/yoshione/fingen/adapter/AdapterBudget.java
index 24a9d1a..2a51db1 100644
--- a/app/src/main/java/com/yoshione/fingen/adapter/AdapterBudget.java
+++ b/app/src/main/java/com/yoshione/fingen/adapter/AdapterBudget.java
@@ -153,7 +153,7 @@ public class AdapterBudget extends RecyclerView.Adapter {
         @Override
         public void onClick(View v) {
             long id = mNode.getmCategory().getID();
-            if (onItemClickListener != null & (id >= 0 | id < BUDGET_ITEM_DEBTS_ROOT) & !mNode.isHasChildren()) {
+            if (onItemClickListener != null & (id >= 0 | id < BUDGET_ITEM_DEBTS_ROOT)) {
                 onItemClickListener.onItemClick(mNode.getmCategory(), mYear, mMonth, mCabbageId, mPosition,mAmount);
             }
         }
diff --git a/app/src/main/java/com/yoshione/fingen/dao/CategoriesDAO.java b/app/src/main/java/com/yoshione/fingen/dao/CategoriesDAO.java
index aa54e7f..75657a5 100644
--- a/app/src/main/java/com/yoshione/fingen/dao/CategoriesDAO.java
+++ b/app/src/main/java/com/yoshione/fingen/dao/CategoriesDAO.java
@@ -192,7 +192,6 @@ public class CategoriesDAO extends BaseDAO implements AbstractDAO, IDaoInheritor
                         "       WHERE\n" +
                         "           (ref_Categories._id = CASE WHEN prod.CategoryID < 0 THEN t.Category ELSE prod.CategoryID END)\n" +
                         "           AND (Currency = ref_Currencies._id)\n" +
-                        "           AND (DestAccount < 0)\n" +
                         "           AND (DateTime >= %s)\n" +
                         "           AND (DateTime <= %s)\n" +
                         "           AND ref_Categories.Deleted = 0\n" +
diff --git a/app/src/main/java/com/yoshione/fingen/managers/CategoryManager.java b/app/src/main/java/com/yoshione/fingen/managers/CategoryManager.java
index de85054..84d4bc2 100644
--- a/app/src/main/java/com/yoshione/fingen/managers/CategoryManager.java
+++ b/app/src/main/java/com/yoshione/fingen/managers/CategoryManager.java
@@ -46,7 +46,6 @@ public class CategoryManager {
         BudgetForCategory budget = root.getmCategory().getBudget();
         for (CNode node : root.getmChildren()) {
             if (node.isHasChildren()) {
-                node.getmCategory().getBudget().setmSums(new ListSumsByCabbage());
                 updatePlanAndFactForParents(node);
             }
             if (budget != null) {
`
Это будет выглядеть примерно так: 
![001](https://user-images.githubusercontent.com/38710216/65033246-f2dea280-d987-11e9-968f-169ed65bba0d.png)
Код не доработан. Он всего лишь разрешает редактировать и отображать подкатегории. Не верно считается нижний Приход, Расход и Итого. Слишком глубоко пришлось ковыряться - не разобрался, а сам не пользуюсь. Здесь в бюджет еще добавлено отображение переводов между своими счетами, если для них указать Категорию, я это использую для откладывания денег на свой счет.
